wso2/docs-apk

- docs/.vuepress/config.js
- docs/.vuepress/enhanceApp.js
- docs/get-started/basic-flow/api-proxy/README.md
- docs/reachout/README.md
- Fixed nav issue
- https://github.com/wso2/docs-apk/issues/18
> Fixed nav issue

- docs/.vuepress/enhanceApp.js
- Updated link redirection related code
> Updated link redirection related code

- en/docs/get-started/dummy.md
- This is PR to test the pipeline.
> Testing pipeline 2

- en/docs/get-started/dummy.md
> test pipeline3

- en/docs/catalogs/overview.md
> Pipeline test4

- en/mkdocs.yml
> Remove unnecessary dependencies

- en/mkdocs.yml
> Removing cutomizations

- en/mkdocs.yml
> remove mkdocs include

- en/mkdocs.yml
> remove custom theme dir

- en/theme/material/templates/2-column.html
- en/theme/material/templates/no-nav.html
- en/theme/material/templates/redoc.html
- en/theme/material/templates/single-column.html
- en/theme/material/templates/swagger.html
- Added Themes> material> templates
> added templates

- en/mkdocs.yml
> updating base path

- en/docs/index.md
- en/docs/restapi/overview.md
- updated links
- updated formatting
> updated links

- en/docs/assets/css/theme.css
- en/mkdocs.yml
- en/theme/material/partials/footer.html
Fixing the footer copyright and the mobile look of the banner. https://github.com/wso2/docs-apk/issues/54
> Fixing the mobile version issue and the footer copyright

- en/docs/catalogs/admin-api.yaml
- en/docs/catalogs/api-catalog.md
- en/docs/catalogs/api-reference-admin.md
- en/docs/catalogs/api-reference-back-office.md
- en/docs/catalogs/api-reference-developer-portal.md
- en/docs/catalogs/api-reference-runtime.md
- en/docs/catalogs/backoffice-api.yaml
- en/docs/catalogs/devportal-api.yaml
- en/docs/catalogs/runtime-api.yaml
- en/mkdocs.yml
Add the all the APK REST API catalogs.
Check the comments below for the respective screenshots.
> Added APK REST API catalogs

- en/docs/apk-deck/identity-platform/idp/idp-overview.md
- en/docs/apk-deck/identity-platform/idp/non-production-idp.md
- en/theme/material/partials/footer.html
1. updated the footer
2. Also fixes https://github.com/wso2/docs-apk/issues/75
> fixes multiple issues

- en/docs/apk-deck/identity-platform/idp/non-production-idp.md
- fixes https://github.com/wso2/docs-apk/issues/75
> fixes https://github.com/wso2/docs-apk/issues/75

- en/docs/administration/organizations.md
- en/docs/get-started/quick-start-guide.md
- Updated the QSG
- fixes https://github.com/wso2/docs-apk/issues/77
> Updated the QSG

- en/docs/catalogs/api-catalog.md
- en/docs/index.md
> Fixed links

- en/docs/apk-deck/identity-platform/idp/asgardeo-idp.md
- en/docs/apk-deck/identity-platform/idp/auth0-idp.md
- en/docs/apk-deck/identity-platform/third-party-idp.md
- en/mkdocs.yml
- Adding 3rd party Idp doc - https://github.com/wso2/docs-apk/issues/90
- Updated Auth0 and Asgardeo IdP docs - https://github.com/wso2/docs-apk/issues/81
> Adding 3rd party Idp doc

- en/docs/catalogs/api-catalog.md
- en/docs/catalogs/api-reference-admin.md
- en/docs/catalogs/api-reference-back-office.md
- en/docs/catalogs/api-reference-developer-portal.md
- en/docs/catalogs/api-reference-runtime.md
- en/docs/index.md
- fixes https://github.com/wso2/docs-apk/issues/98
> added relative paths

- en/docs/apk-deck/identity-platform/idp/asgardeo-idp.md
- en/docs/apk-deck/identity-platform/idp/auth0-idp.md
- en/docs/apk-deck/identity-platform/idp/idp-overview.md
- en/docs/apk-deck/identity-platform/idp/third-party-idp.md
- en/docs/develop-and-deploy-api/api-policies/attach-policies-via-rest-api.md
- en/docs/index.md
- Fixes https://github.com/wso2/docs-apk/issues/90
- Fixes https://github.com/wso2/docs-apk/issues/96
- Minor formatting fixes
> fixes #96 and #90

- en/docs/catalogs/admin-api.yaml
- en/docs/catalogs/backoffice-api.yaml
- en/docs/catalogs/devportal-api.yaml
- en/docs/catalogs/runtime-api.yaml
- fixes https://github.com/wso2/docs-apk/issues/82
- fixes https://github.com/wso2/docs-apk/issues/83
- fixes https://github.com/wso2/docs-apk/issues/84
- fixes https://github.com/wso2/docs-apk/issues/89
> updated catalogs for M6

- en/theme/material/templates/redoc.html
> Fix a minor style issue in the layout template

- en/docs/administration/organizations.md
Fixes https://github.com/wso2/docs-apk/issues/97
> updated org creation flow #97

- en/docs/administration/organizations.md
Updated org parameter descriptions based on input given by Krishan.
https://github.com/wso2/docs-apk/issues/97
> Updated org parameter descriptions

- en/docs/assets/css/redoc.css
- en/mkdocs.yml
- en/theme/material/main.html
- en/theme/material/templates/redoc.html
> Fixing the redoc to work with the new theme

- en/docs/apk-deck/identity-platform/idp/idp-overview.md
- en/docs/index.md
- fixed broken links
- fixes https://github.com/wso2/docs-apk/issues/127
> fixed broken links

- en/docs/catalogs/backoffice-api.yaml
- updated all the backoffice `x-code-samples` to generate the cURL commands.
https://github.com/wso2/docs-apk/issues/134
> [BackOffice] updated x-code-samples

- en/docs/catalogs/runtime-api.yaml
- Added  `x-code-samples` to the YAML file (`en/docs/catalogs/runtime-api.yaml`) in order to get Sample cURL commands to render in the Runtime API catalog.
- Updated the messaging. Checked grammar, typos and overall messaging.
https://github.com/wso2/docs-apk/issues/120
> [Runtime] Added x-code-samples

- .vscode/settings.json
- en/docs/assets/css/apktheme.css
- en/docs/assets/css/config-catalog.css
- en/docs/assets/css/theme.css
- en/docs/assets/js/apktheme.js
- en/docs/assets/js/theme.js
- en/docs/includes/apply-cr.md
- en/docs/includes/crs-samples.md
- en/docs/includes/start-apk.md
- en/mkdocs.yml
- en/theme/material/templates/redoc.html
> Adding dark theme toggle and fixed issues with tabbed view

- en/docs/assets/css/apktheme.css
- en/docs/assets/css/redoc.css
- en/docs/assets/css/theme.css
Fixing the catalog page scroll position issues
> Fixing https://github.com/wso2/docs-apk/issues/133

- en/docs/catalogs/backoffice-api.yaml
- Added Minor Formatting in backoffice-api.yaml
> Added Minor Formatting

- en/docs/catalogs/runtime-api.yaml
> add ratelimit related changes into docs

- en/docs/develop-and-deploy-api/api-policies/attach-policies-via-crs.md
- en/docs/develop-and-deploy-api/api-policies/attach-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/rate-limiting-policy-overview.md
- en/docs/develop-and-deploy-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
- en/docs/develop-and-deploy-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/mkdocs.yml
- Added the following pages with regard to the rate limiting feature
-  Rate Limiting Overview
- Add Rate Limiting Policy via the REST API Interface
- Add Rate Limiting Policy via CRs
- fixes https://github.com/wso2/docs-apk/issues/137
**Overview**
**REST API**
**CR**
> Added rate limiting docs

- en/docs/catalogs/runtime-api.yaml
- fixes https://github.com/wso2/docs-apk/issues/151
> Added endpoint-certificates API

- en/docs/catalogs/runtime-api.yaml
- Sync https://github.com/wso2/apk/pull/970
> Update resources used to validate OpenApi definitions

- en/docs/setup/migration.md
- en/mkdocs.yml
> Add initial migration doc for APK

- en/docs/develop-and-deploy-api/api-policies/interceptors.md
- en/mkdocs.yml
> Interceptor APIPolicy docs

- en/docs/create-api/create-api-overview.md
> Remove .md in path to remove warning

- en/docs/index.md
> Fixing document issues

- en/docs/setup/identity-platform/idp/asgardeo-idp.md
- en/docs/setup/identity-platform/idp/auth0-idp.md
- en/docs/setup/identity-platform/idp/idp-overview.md
- en/docs/setup/identity-platform/idp/non-production-idp.md
- en/docs/setup/identity-platform/idp/third-party-idp.md
- en/mkdocs.yml
move identity provider from apk-deck->setup
> move identity provider from apk-deck->setup

- en/docs/index.md
> Improve main page with details related to quick start guide

- en/docs/create-api/manage-service-endpoint/manage-security-via-crs.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-rest-api.md
- en/mkdocs.yml
This will add the docs for Basic auth endpoint security.
- https://github.com/wso2/apk/pull/977
> Add basic auth endpoint security docs

- en/docs/create-api/manage-service-endpoint/manage-security-via-rest-api.md
Changed the example format of the secret
> Change format of the secret

- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-overview.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
- en/docs/create-api/create-and-deploy-apis/create-api-using-cr.md
> Updated API, APIPolicy CR changes

- en/docs/create-api/rate-limiting/custom-rate-limiting.md
Add a reference to the sample custom ratelimit interceptor service folder in project repo
> Custom rate limiting: reference sample link added

- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
- en/docs/create-api/rate-limiting/custom-rate-limiting.md
> Referring to the mediation interceptor samples from docs

- en/docs/create-api/rate-limiting/custom-rate-limiting.md
> Custom rate limiting: reference sample link corrected

- en/docs/includes/start-apk.md
Getting started page tabs are not formated properly.
> Fixing the tabs not formatted issue

- en/mkdocs.yml
> fix base_path as images are not loading

- en/docs/create-api/manage-service-endpoint/manage-certificate.md
> Configuring SAN verification of the backend certificate

- en/docs/administration/configurations/configure-logs-enforcer.md
- en/docs/administration/configurations/configure-logs-router.md
> Fixing doc content issues

- en/docs/catalogs/config-catalog.md
- en/mkdocs.yml
> add helm docs

- en/docs/setup/configure-analytics-for-elk-stack.md
- en/mkdocs.yml
This PR adds docs to configure analytics for ELK stack in APK.
Related to https://github.com/wso2/apk/issues/1127
> Add docs for analytics for ELK stack

- README.md
- en/docs/create-api/create-and-attach-api-policies/cors/enable-cors-via-crs.md
- en/mkdocs.yml
Add docs for CORS policy. This doc PR is related to https://github.com/wso2/apk/issues/582.
> Add docs for CORS policy

- en/docs/administration/configurations/configure-logs-enforcer.md
> $subject
> Related PRs: https://github.com/wso2/apk/pull/1305
> Add trace logs

- en/docs/get-started/quick-start-guide.md
fixing minor issue in file name
> Fixing minor issue in file name

- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/mkdocs.yml
fixes https://github.com/wso2/docs-apk/issues/219
> Adding API version docs

- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
> Fix format

- en/docs/develop-and-deploy-api/api-versions/default-version.md
> Add default api version

- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
- en/mkdocs.yml
> Add production and sandbox endpoints

- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/jwt.md
- en/mkdocs.yml
> Add enable disble jwt

- en/docs/create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api.md
> Add cors via rest

- en/docs/develop-and-deploy-api/api-properties/api-properties.md
- en/docs/setup/listeners/configure-gateway-listeners.md
- en/mkdocs.yml
fixes https://github.com/wso2/docs-apk/issues/228
fixes https://github.com/wso2/docs-apk/issues/231
> adding gateway listener and API Properties docs

- en/docs/get-started/quick-start-guide.md
- en/docs/setup/deploy-in-openshift.md
> Add OpenShift configurations

- en/docs/setup/analytics/configure-analytics-for-elk-stack.md
> Update ELK Analytics configurations

- en/docs/setup/identity-platform/idp/asgardeo-idp.md
> Fix broken links in Asgardeo as an IdP doc page

- en/docs/develop-and-deploy-api/jwt-issuers/jwt-issuers.md
- en/docs/get-started/quick-start-guide.md
- en/mkdocs.yml
fixes: https://github.com/wso2/docs-apk/issues/237
> Adding new jwt issuer

- en/mkdocs.yml
> Add OpenShift Docs under Setup

- en/docs/create-api/create-and-deploy-apis/direct-undeploy.md
- en/mkdocs.yml
fixes: https://github.com/wso2/docs-apk/issues/240
> Adding undeploy API doc

- en/docs/setup/identity-platform/idp/idp-overview.md
- en/docs/setup/identity-platform/idp/third-party-idp.md
>  Add note about JWT issuer in IdP docs 

- en/docs/create-api/manage-service-endpoint/manage-resiliency-circuit-breaker.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-timeout.md
- en/mkdocs.yml
- Add documentation for backend timeouts, retry policies and circuit breakers.
> Add documentation for backend resiliency

- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
> Fix k8s manifests in interceptor CR docs

- en/docs/catalogs/api-catalog.md
- en/docs/catalogs/api-reference-config-deployer.md
- en/docs/catalogs/api-reference-config-generator.md
- en/docs/catalogs/api-reference-runtime.md
- en/mkdocs.yml
fixes: https://github.com/wso2/docs-apk/issues/246
> Adding API catalog doc changes

- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-overview.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
> Move interceptor service sample to Interceptor Overview

- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-rest-api.md
> Fix interceptor policy name

- en/docs/catalogs/api-cr.md
- en/docs/catalogs/api-policy.md
- en/docs/catalogs/backend-jwt.md
- en/docs/catalogs/kubernetes-crds.md
- en/docs/catalogs/rate-limit-policy.md
- en/mkdocs.yml
fixes: https://github.com/wso2/docs-apk/issues/249
> adding crd changes in catalog

- en/docs/catalogs/ratelimit-custom.md
- en/docs/create-api/rate-limiting/custom-rate-limiting.md
fixes: https://github.com/wso2/docs-apk/issues/253
> Fixing custom ratelimit docs

- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/mkdocs.yml
fixes: https://github.com/wso2/docs-apk/issues/258
> adding API Definition Endpoint docs

- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
> Update backend JWT token manipulation docs

- en/docs/create-api/manage-service-endpoint/manage-security-via-rest-api.md
- Remove content related to Runtime DS and add apk-conf related documentation
> Update backend security documentation

- en/docs/catalogs/ratelimit-api.md
- en/docs/catalogs/ratelimit-custom.md
- en/docs/catalogs/ratelimit-resource.md
- en/docs/create-api/create-and-attach-api-policies/api-policies-overview.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-overview.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
- en/docs/create-api/manage-service-endpoint/manage-certificate.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/jwt.md
> Updated code snippets in simple rate limit docs

- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api.md
- en/docs/create-api/create-and-deploy-apis/direct-deploy.md
- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/docs/develop-and-deploy-api/api-properties/api-properties.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/jwt.md
- en/docs/get-started/quick-start-guide.md
fixes https://github.com/wso2/docs-apk/issues/262
> Removing organization and vhost from apk-confs

- en/docs/setup/identity-platform/idp/asgardeo-idp.md
- en/docs/setup/identity-platform/idp/auth0-idp.md
> Updating Auth0 flow in IDP docs

- en/docs/administration/distributed-tracing.md
> $subject
> Git Issue: https://github.com/wso2/apk/issues/1471
> Update docs on rate limiter tracing restrictions

- en/docs/setup/prerequisites.md
need to add pre-requisite exact versions
> adding pre-requisite exact versions

- en/docs/setup/prerequisites.md
> adding rancher requirements

- en/docs/develop-and-deploy-api/api-scopes/api-scopes.md
- en/mkdocs.yml
fixes: https://github.com/wso2/docs-apk/issues/268
> adding API scopes docs

- en/docs/setup/prerequisites.md
- en/mkdocs.yml
Refactoring requirements table
> Refactoring requirements table

- en/docs/includes/start-apk.md
- en/docs/setup/install.md
- en/mkdocs.yml
> Adding helm install guide

- en/docs/catalogs/ratelimit-api.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
> Updating targetRefs in RateLimitPolicy

- en/docs/create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-timeout.md
> Update docs for backend timeout

- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/create-api/rate-limiting/rate-limiting-policy-overview.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/get-started/quick-start-guide.md
fixes: https://github.com/wso2/docs-apk/issues/288
fixes: https://github.com/wso2/docs-apk/issues/286
fixes: https://github.com/wso2/docs-apk/issues/277
> Fixing several doc issues

- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/security/generate-access-token.md
- en/mkdocs.yml
fixes: https://github.com/wso2/docs-apk/issues/281
fixes: https://github.com/wso2/docs-apk/issues/280
fixes: https://github.com/wso2/docs-apk/issues/279
> Fixing API policy CR approach and Add separate generate Access Token docs issues

- en/docs/administration/configurations/configure-logs-adapter.md
- en/docs/administration/configurations/configure-logs-enforcer.md
- en/docs/administration/configurations/configure-logs-overview.md
- en/docs/administration/configurations/configure-logs-router.md
- en/docs/administration/distributed-tracing.md
- en/docs/includes/Customizing-Helm-Deployment-Configurations.md
- en/docs/includes/start-apk.md
> Fixes: https://github.com/wso2/docs-apk/issues/290, https://github.com/wso2/docs-apk/issues/275
> Instructions to use values.yaml

- en/docs/create-api/create-and-attach-api-policies/api-policies-overview.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-overview.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-rest-api.md
- Fix https://github.com/wso2/docs-apk/issues/284
- Fix https://github.com/wso2/docs-apk/issues/274
- Fix https://github.com/wso2/docs-apk/issues/283
- Change resource level policy name to operation level policy for consistency
- Add complete apk-conf file to interceptor documentation examples
> Fixing several issues in API policy related documentation

- en/docs/create-api/create-and-deploy-apis/create-and-deploy-api.md
- en/docs/includes/start-apk.md
fixes: https://github.com/wso2/docs-apk/issues/293
fixes: https://github.com/wso2/docs-apk/issues/294
> Fixing k8s cr generation related docs

- en/docs/create-api/create-and-deploy-apis/apk-conf-lang-support.md
- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/create-api/create-and-deploy-apis/tools-for-api-development.md
- en/mkdocs.yml
> Fixes: https://github.com/wso2/docs-apk/issues/287
> Add VS Code Plugin related docs

- en/docs/create-api/create-and-deploy-apis/apk-conf-lang-support.md
> Relatesd PRs: https://github.com/wso2/docs-apk/pull/304
> Add VS Code Marketplace link

- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/jwt.md
> Fix formatting issues in [1],[2]
[1] https://apk.docs.wso2.com/en/latest/develop-and-deploy-api/security/authentication/enable-api-security/jwt/
[2] https://apk.docs.wso2.com/en/latest/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint/
> Fix formatting issues

- en/docs/setup/analytics/configure-analytics-for-choreo-insights.md
> Fix link to choreo

- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
> $subject
> Fixes: https://github.com/wso2/docs-apk/issues/306
> Add try out scenarios for ratelimit policies via REST API

- en/docs/administration/distributed-tracing.md
> Fix duplicated configs in distributed tracing
> Fix duplicated tracing configs

- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
This PR fixes https://github.com/wso2/docs-apk/issues/312
> Fix sandbox endpoint host

- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-rest-api.md
- Fix multiple issues with the interceptor via CR docs.
- Add response interceptorservice CR sample.
- Sync the example given with the examples given in via CR section.
- Add documentation for apk-conf interceptor service tls support.
> Update interceptor service documentation

- en/docs/setup/deploy-in-openshift.md
> Update helm chart versions for OpenShift

- en/docs/administration/configurations/configure-logs-adapter.md
- en/docs/administration/configurations/configure-logs-enforcer.md
- en/docs/administration/configurations/configure-logs-router.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/get-started/quick-start-guide.md
fixes: https://github.com/wso2/docs-apk/issues/307
fixes: https://github.com/wso2/docs-apk/issues/276
> Fixing log configuration and required fields issue

- en/docs/setup/deploy-in-openshift.md
> Add RC tags for OpenShift deployment

- en/docs/setup/Customize-Configurations.md
> Use helm command to download values yaml

- en/docs/setup/deploy-in-openshift.md
> Update gateway service in OpenShift deployment

- en/docs/about-apk/performance-test-results/overview.md
> Upade concurrency value

- en/docs/catalogs/backend-jwt.md
- en/docs/catalogs/backend.md
- en/docs/catalogs/kubernetes-crds.md
- en/docs/catalogs/rate-limit-policy.md
- en/docs/catalogs/ratelimit-api.md
- en/docs/catalogs/ratelimit-custom.md
- en/docs/catalogs/ratelimit-resource.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/create-api/rate-limiting/custom-rate-limiting.md
> Add Rate Limit and BackendJWT catalog syntax descriptions

- en/docs/catalogs/ratelimit-custom.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-rest-api.md
- en/docs/create-api/rate-limiting/custom-rate-limiting.md
> Update custom rate limit policy docs

- en/docs/get-started/quick-start-guide.md
- en/docs/includes/start-apk.md
- en/docs/setup/Customize-Configurations.md
> Update QSG docs

- en/docs/catalogs/api-cr.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
- en/docs/create-api/create-and-deploy-apis/create-api-using-cr.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/oauth2.md
- en/docs/develop-and-deploy-api/token-issuers/token-issuers.md
- en/docs/get-started/quick-start-guide.md
- en/docs/setup/identity-platform/idp/idp-overview.md
- en/mkdocs.yml
> add renaming changes

- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/oauth2.md
add passthrough authorization header
> add passthrough authorization header

- en/docs/setup/prerequisites.md
Refactoring pre-requisite page
> Refactoring pre-requisite page

- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/get-started/quick-start-guide.md
> Remove apiType filed when generating apk conf

- en/docs/about-apk/FAQs.md
- en/docs/includes/start-apk.md
> Add crd apply step

- en/docs/catalogs/interceptors.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-overview.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-crs.md
- en/docs/create-api/create-and-deploy-apis/create-api-using-cr.md
- en/docs/create-api/manage-service-endpoint/manage-certificate.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-circuit-breaker.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-timeout.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-crs.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-rest-api.md
- en/docs/develop-and-deploy-api/token-issuers/token-issuers.md
- en/docs/get-started/quick-start-guide.md
- en/docs/includes/apply-cr.md
- en/docs/includes/start-apk.md
- en/docs/setup/Customize-Configurations.md
- en/docs/setup/deploy-in-openshift.md
- en/docs/setup/identity-platform/idp/asgardeo-idp.md
- en/docs/setup/identity-platform/idp/auth0-idp.md
- en/docs/setup/identity-platform/idp/third-party-idp.md
Fixes https://github.com/wso2/docs-apk/issues/350 : We don't have to specifically mention namespaces in our docs as we do support deploying in default namespace also.
namespaces come into play when there are namespace base dataplanes or if a user wants to use another namespace for APK related CRs. 
> Brief description of the new feature or bug fix as it will appear in the …
> Remove namespace from examples

- en/docs/create-api/create-and-deploy-apis/create-and-deploy-api.md
> Remove apiType from k8 resource generation

- en/docs/get-started/quick-start-guide.md
> Remove api type from the table

- en/docs/about-apk/FAQs.md
- en/docs/get-started/quick-start-guide.md
- en/docs/includes/start-apk.md
> Add how to uninstall faq

- en/docs/catalogs/crds/api_types.md
- en/docs/catalogs/crds/apipolicy_types.md
- en/docs/catalogs/crds/authentication_types.md
- en/docs/catalogs/crds/backend_types.md
- en/docs/catalogs/crds/backendjwt_types.md
- en/docs/catalogs/crds/interceptorservice_types.md
- en/docs/catalogs/crds/ratelimitpolicy_types.md
- en/docs/catalogs/crds/scope_types.md
- en/docs/catalogs/crds/tokenIssuer_types.md
- en/docs/catalogs/kubernetes-crds.md
- en/docs/catalogs/samples/api-cr.md
- en/docs/catalogs/samples/api-policy.md
- en/docs/catalogs/samples/authentication.md
- en/docs/catalogs/samples/backend-jwt.md
- en/docs/catalogs/samples/backend.md
- en/docs/catalogs/samples/cors.md
- en/docs/catalogs/samples/http-route.md
- en/docs/catalogs/samples/interceptor-policy.md
- en/docs/catalogs/samples/interceptor-service.md
- en/docs/catalogs/samples/ratelimit-api.md
- en/docs/catalogs/samples/ratelimit-custom.md
- en/docs/catalogs/samples/scope.md
- en/docs/catalogs/samples/token-issuer.md
- en/mkdocs.yml
> Update CRD catalog docs

- en/docs/catalogs/samples/backend.md
- en/docs/catalogs/samples/token-issuer.md
- en/docs/create-api/create-and-deploy-apis/create-and-deploy-api.md
- en/docs/create-api/create-and-deploy-apis/direct-undeploy.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-crs.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-rest-api.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
- en/docs/setup/prerequisites.md
- en/mkdocs.yml
> Fix minor formatting issues

- en/theme/material/main.html
> Removing wip banner

- en/docs/about-apk/FAQs.md
- en/docs/about-apk/performance-test-results/overview.md
- en/docs/create-api/create-and-deploy-apis/create-api-using-cr.md
- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/create-api/manage-service-endpoint/manage-certificate.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/oauth2.md
- en/docs/includes/start-apk.md
- Updates the FAQs page
- Fixes #376 
- Fixes minor formatting issues
> Update FAQs page

- en/docs/create-api/create-and-deploy-apis/create-api-using-cr.md
- en/docs/create-api/create-and-deploy-apis/create-api-using-enhanced-flow.md
- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/create-api/create-and-deploy-apis/tools-for-api-development.md
- en/docs/create-api/create-api-overview.md
- en/mkdocs.yml
Fixes https://github.com/wso2/docs-apk/issues/384
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Review api deploy docs

- en/docs/create-api/manage-service-endpoint/manage-security-via-crs.md
> Add a try out section to basic auth EP security docs

- en/mkdocs.yml
Moves FAQs To a new section.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Add a FAQ section

- en/docs/includes/start-apk.md
Adding open source apk install approach
> Adding open source apk install approach

- en/docs/assets/files/get-started/EmployeeServiceDefinition.json
- en/docs/create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api.md
- en/docs/create-api/create-and-deploy-apis/direct-deploy.md
- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/docs/develop-and-deploy-api/api-properties/api-properties.md
- en/docs/develop-and-deploy-api/api-scopes/api-scopes.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/oauth2.md
- en/docs/get-started/quick-start-guide.md
fixes https://github.com/wso2/docs-apk/issues/390
fixes https://github.com/wso2/docs-apk/issues/394
> Fixing grammer issues in QSG and Backend Issue

- en/docs/index.md
> Update download link

- en/docs/control-plane/apim-apk-agent-deploy.md
- en/docs/control-plane/apim-apk-agent-overview.md
- en/docs/control-plane/apim-deploy.md
- en/docs/control-plane/apk-deploy.md
- en/docs/control-plane/control-plane-configuration.md
- en/docs/control-plane/control-plane-deployment.md
- en/docs/control-plane/overview.md
- en/mkdocs.yml
> Update agent doc

- en/docs/control-plane/api-management/control-plane-create-and-deploy-apis.md
- en/docs/control-plane/api-management/control-plane-create-application-and-subscription.md
- en/docs/control-plane/api-management/control-plane-operations.md
- en/docs/control-plane/apim-apk-agent-deploy.md
- en/docs/control-plane/apim-deploy.md
- en/docs/control-plane/apk-deploy.md
- en/docs/control-plane/control-plane-qsg.md
- en/mkdocs.yml
Adding control plane related doc changes
> Adding control plane related doc changes

- README.md
> [1.0.0] Update README.md

- README.md
> [1.1.0] Update README.md

- en/theme/material/main.html
> [1.1.0] Add WIP banner

- en/docs/administration/prometheus-metric-support.md
- en/mkdocs.yml
> Adds the configurations and metrics exposed by Prometheus in the APK.
Fixes #411
> Add documentation for the Prometheus feature

- en/docs/control-plane/control-plane-qsg.md
Adding agent helm install commands for 1.1.0-alpha
> Adding agent helm install commands for 1.1.0-alpha

- .gitignore
> [versions] Update .gitignore

- en/docs/control-plane/control-plane-qsg.md
- en/docs/includes/start-apk.md
Changing apk qsg to 1.1.0-alpha
> Changing apk qsg to 1.1.0-alpha

- en/mkdocs.yml
> Fix menu titles

- en/docs/assets/css/apktheme.css
- en/docs/index.md
- en/mkdocs.yml
- en/theme/material/base.html
- en/theme/material/main.html
- en/theme/material/templates/versions.html
> Update versions page in the staging site

- en/docs/assets/js/theme.js
> Sync versions-dev with versions

- en/docs/assets/css/theme.css
This PR is to hide the versions dropdown from the UI.
> Update theme.css in versions-dev page

- en/mkdocs.yml
> [1.1.0]Fix menu titles

- en/docs/catalogs/crds/api_types.md
- en/docs/catalogs/crds/apipolicy_types.md
- en/docs/catalogs/crds/application_mapping_types.md
- en/docs/catalogs/crds/application_types.md
- en/docs/catalogs/crds/authentication_types.md
- en/docs/catalogs/crds/gql_routes_types.md
- en/docs/catalogs/crds/interceptorservice_types.md
- en/docs/catalogs/crds/subscription_types.md
- en/docs/catalogs/crds/tokenIssuer_types.md
- en/docs/catalogs/samples/api-cr.md
- en/docs/catalogs/samples/application.md
- en/docs/catalogs/samples/application_mapping.md
- en/docs/catalogs/samples/authentication.md
- en/docs/catalogs/samples/subscription.md
- en/docs/catalogs/samples/token-issuer.md
- en/mkdocs.yml
> Update CRDs in the documentation catalog

- en/docs/control-plane/api-management/control-plane-add-apk-gateway.md
- en/docs/control-plane/api-management/control-plane-create-and-deploy-rest-apis.md
- en/docs/control-plane/apim-apk-agent-deploy.md
- en/docs/control-plane/control-plane-configuration.md
- en/docs/control-plane/control-plane-qsg.md
- en/mkdocs.yml
Adding initial changes to cp graphql docs
> Adding initial changes to cp graphql docs

- en/docs/administration/prometheus-metric-support.md
- en/docs/assets/files/get-started/StarWarsAPI.graphql
- en/docs/control-plane/api-management/control-plane-create-and-deploy-graphql-apis.md
- en/docs/create-api/create-and-deploy-apis/graphql/create-graphql-api-using-crs.md
- en/docs/create-api/create-and-deploy-apis/graphql/create-graphql-api.md
- en/docs/create-api/create-and-deploy-apis/rest/create-rest-api-using-crs.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/get-started/quick-start-guide.md
- en/mkdocs.yml
This PR adds documentation for the GraphQL feature.
Fixes #445
> Add documentation for GraphQL feature

- en/docs/assets/css/blue-palette-alt1.css
- en/docs/assets/css/theme.css
- en/mkdocs.yml
- en/theme/material/base.html
- en/theme/material/main.html
- en/theme/material/partials/copyright.html
- en/theme/material/partials/footer.html
- en/theme/material/partials/header.html
This PR is to customize the styling on the versions page.
> Customize styling on the versions page

- en/docs/assets/css/apktheme.css
- en/docs/assets/js/apktheme.js
- en/mkdocs.yml
- en/theme/material/partials/header.html
This PR is to add the custom dropdown component and its styling to the 1.1.0-dev branch.
> Add custom dropdown component

- en/docs/index.md
> Remove comments

- en/docs/assets/versions.json
- en/docs/index.md
> Update versions page with the latest release info

- en/docs/assets/js/apktheme.js
> Update versions.json path

- en/docs/assets/versions.json
- en/docs/index.md
> Revert "Update versions page with the latest release info"

- .gitignore
This PR is to ignore the generated output files (HTML and others) from the PRs.
> [1.0.0] Update .gitignore

- .gitignore
This PR is to ignore the generated output files (HTML and others) from the PRs.
> [1.1.0] Update .gitignore

- .gitignore
This PR is to ignore the generated output files (HTML and others) from the PRs.
> [main] Update .gitignore

- en/docs/control-plane/apim-deploy.md
- en/docs/control-plane/control-plane-qsg.md
Fixing APIM gateway environment configurations
> Fixing APIM gateway environment configurations and QSG for CP to DP

- en/docs/includes/start-apk.md
> Changing to alpha2 in DP QSG

- en/docs/get-started/quick-start-guide-with-cp.md
- en/docs/get-started/quick-start-guide.md
Fixing config deployer url version
> Fixing config deployer url version

- en/docs/control-plane/control-plane-qsg.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
> Changing helm values to beta

- en/docs/control-plane/api-management/control-plane-create-and-deploy-rest-apis.md
- en/docs/control-plane/api-management/control-plane-create-application-and-subscription.md
- en/docs/control-plane/control-plane-qsg.md
Fixing several issues in CP to DP QSG docs
> Fixing several issues in CP to DP QSG docs

- en/docs/assets/js/apktheme.js
This PR is to maintain the URL path when switching between versions in the 1.0.0-dev (staging) branch.
> Maintain URL path when switching between versions

- en/docs/assets/css/apktheme.css
- en/docs/assets/js/apktheme.js
- en/theme/material/partials/header.html
- This PR is to add the custom dropdown component, its functionalities and style adjustments.
- It includes a code block to temporarily hide the dropdown from the UI until the next release [added via 9b899689436fbea7e18a95ef6adaa9c29344b84e]. Hence, until it is removed, the dropdown will remain hidden.
- It also includes a fix to maintain the URL path when switching between versions (to remain on the same page when switching the versions).
> [1.1.0] Add custom dropdown component

- en/docs/control-plane/control-plane-qsg.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
> Changing docs to RC

- en/docs/control-plane/control-plane-qsg.md
- en/docs/includes/start-apk-cp.md
> Changing qsg to rc2

- en/docs/includes/start-apk.md
> changing dp qsg to rc2

- en/docs/control-plane/api-management/control-plane-create-and-deploy-rest-apis.md
- en/docs/control-plane/api-management/control-plane-create-application-and-subscription.md
- en/docs/control-plane/control-plane-qsg.md
- en/docs/get-started/quick-start-guide-with-cp.md
Adding host setting and hyperlink properly for apim
> Adding host setting and hyperlink properly for apim

- en/docs/get-started/quick-start-guide-with-cp.md
> Update Dp to CP doc

- en/docs/assets/css/apktheme.css
> Add version dropdown

- en/docs/control-plane/api-management/control-plane-create-and-deploy-rest-apis.md
> Add namespace to command

- en/docs/control-plane/control-plane-qsg.md
> Add insecure mode to curl request

- en/mkdocs.yml
> Hide apipolicy

- en/docs/index.md
Add download link to 1.1.0 release tag
> Add download link to 1.1.0 release tag

- en/docs/assets/versions.json
Adding latest version to versions file
> Adding latest version to versions file

- en/docs/assets/versions.json
> Revert "Adding latest version to versions file"

- en/docs/setup/migration.md
> fixing docs

- en/docs/includes/start-apk.md
- en/docs/setup/Customize-Configurations.md
> Add enterprise approach to 1.0.0 QSG

- en/docs/setup/analytics/configure-analytics-for-choreo-insights.md
- en/docs/setup/analytics/configure-analytics-for-elk-stack.md
- en/docs/setup/analytics/configure-analytics-for-moesif.md
> Fix formatting issues in analytics documentation

- en/docs/api-management-overview/create-api-overview.md
- en/docs/api-management-overview/create-api-using-crs.md
- en/docs/api-management-overview/tools-for-api-development.md
- en/docs/catalogs/kubernetes-crds.md
- en/docs/create-api/create-and-deploy-apis/create-and-deploy-api.md
- en/docs/create-api/create-and-deploy-apis/direct-deploy.md
- en/docs/create-api/create-and-deploy-apis/direct-undeploy.md
- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/create-api/create-and-deploy-apis/graphql/create-graphql-api.md
- en/docs/create-api/create-and-deploy-apis/rest/create-rest-api-using-crs.md
- en/docs/create-api/create-api-overview.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/templates/create-sample-backend.md
- en/mkdocs.yml
Fixes https://github.com/wso2/docs-apk/issues/549
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Add overiew explaining the the CR and restapi modes in DP

- en/docs/get-started/quick-start-guide.md
- en/docs/setup/uninstall.md
- en/mkdocs.yml
> [1.0.0] Add uninstall instructions for APK

- en/docs/page-not-found.md
- en/theme/material/templates/single-column.html
> Adding page not found

- en/docs/api-management-overview/create-api-using-crs.md
- en/docs/api-management-overview/tools-for-api-development.md
> Fix rest api doc link

- en/docs/control-plane/api-management/control-plane-create-and-deploy-graphql-apis.md
- en/docs/control-plane/api-management/control-plane-create-and-deploy-rest-apis.md
Adding dp to cp flow api creation steps for cp
> Adding dp to cp flow api creation steps for cp

- en/docs/control-plane/api-management/control-plane-api-management-overview.md
- en/docs/control-plane/apk-as-gateway-in-apim/api-management/control-plane-api-management-overview.md
> Fixing supported features doc

- en/docs/develop-and-deploy-api/api-versions/semver-based-intelligent-routing.md
- en/mkdocs.yml
> Add semver based intelligent routing docs

- en/docs/setup/multi-env-deployment-on-apk.md
- en/mkdocs.yml
> Add multi-env deployment docs for APK

- en/docs/control-plane/api-management/control-plane-api-management-overview.md
- en/docs/control-plane/apk-as-gateway-in-apim/api-management/control-plane-api-management-overview.md
Refactoring supported feature docs
> Refactoring supported feature docs

- en/docs/setup/install-with-cp.md
- en/mkdocs.yml
> Add new section for CP instalation

- en/docs/create-api/create-and-attach-api-policies/api-policies-overview.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/overview.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-circuit-breaker.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-timeout.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/mkdocs.yml
> [1.0.0] Update API Policy documentation with steps

- en/docs/catalogs/crds/gql_routes_types.md
- en/docs/catalogs/samples/gqlroute.md
- en/docs/create-api/create-and-attach-api-policies/api-policies-overview.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/overview.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-circuit-breaker.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-timeout.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-crs.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/mkdocs.yml
- Adds GraphQL sample to catalog
- Updates backend JWT documentation with steps
- Fixes minor issues in resiliency documentation
- Add overview to backend JWT section
- Fixes #578
> [1.1.0] Update API Policy documentation with steps

- en/docs/includes/customize-installation.md
- en/docs/includes/start-apk.md
> Add no-hooks command for helm upgrade

- en/docs/catalogs/crds/api_types.md
- en/docs/catalogs/crds/apipolicy_types.md
- en/docs/catalogs/crds/authentication_types.md
- en/docs/catalogs/crds/tokenIssuer_types.md
- en/docs/catalogs/samples/api-cr.md
- en/docs/catalogs/samples/api-policy.md
- en/docs/catalogs/samples/interceptor-policy.md
- en/docs/catalogs/samples/ratelimit-api.md
- en/docs/catalogs/samples/ratelimit-custom.md
- en/docs/catalogs/samples/ratelimit-resource.md
- en/docs/create-api/create-and-attach-api-policies/api-policies-overview.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/create-api/rate-limiting/custom-rate-limiting.md
- en/docs/get-started/quick-start-guide.md
- en/docs/setup/analytics/configure-analytics-for-choreo-insights.md
- en/docs/setup/analytics/configure-analytics-for-elk-stack.md
- en/docs/setup/analytics/configure-analytics-for-moesif.md
- en/docs/setup/uninstall.md
This PR fixes the issues pointed out in the following PRs:
- https://github.com/wso2/docs-apk/pull/330
- https://github.com/wso2/docs-apk/pull/340
- https://github.com/wso2/docs-apk/pull/342
- https://github.com/wso2/docs-apk/pull/359
- https://github.com/wso2/docs-apk/pull/362
- https://github.com/wso2/docs-apk/pull/366
- https://github.com/wso2/docs-apk/pull/412
- https://github.com/wso2/docs-apk/pull/475
- https://github.com/wso2/docs-apk/pull/497
- https://github.com/wso2/docs-apk/pull/523
- https://github.com/wso2/docs-apk/pull/554
- https://github.com/wso2/docs-apk/pull/558
> [1.1.0] Fix formatting issues and typos

- en/docs/catalogs/crds/api_types.md
- en/docs/catalogs/crds/apipolicy_types.md
- en/docs/catalogs/crds/authentication_types.md
- en/docs/catalogs/crds/backend_types.md
- en/docs/catalogs/samples/interceptor-policy.md
- en/docs/catalogs/samples/ratelimit-api.md
- en/docs/catalogs/samples/ratelimit-custom.md
- en/docs/catalogs/samples/ratelimit-resource.md
- en/docs/create-api/create-and-attach-api-policies/api-policies-overview.md
- en/docs/create-api/create-and-deploy-apis/generate-apk-conf.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-crs.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/create-api/rate-limiting/custom-rate-limiting.md
- en/docs/setup/analytics/configure-analytics-for-choreo-insights.md
- en/docs/setup/analytics/configure-analytics-for-elk-stack.md
- en/docs/setup/analytics/configure-analytics-for-moesif.md
This PR resolves the issues pointed out as comments in the following PRs:
- https://github.com/wso2/docs-apk/pull/340
- https://github.com/wso2/docs-apk/pull/359
- https://github.com/wso2/docs-apk/pull/330
- https://github.com/wso2/docs-apk/pull/496
- https://github.com/wso2/docs-apk/pull/572
> [1.0.0] Fix formatting issues and typos

- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/get-started/quick-start-guide-with-cp.md
- en/docs/get-started/quick-start-guide.md
- en/docs/setup/enterprise-install.md
- en/mkdocs.yml
Adding enterprise approach for APK 1.1.0 docs
https://github.com/wso2/apk/issues/2404
> Adding enterprise approach for APK 1.1.0 docs

- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/get-started/quick-start-guide-with-cp.md
- en/docs/get-started/quick-start-guide.md
- en/docs/setup/enterprise-apim-apk-agent-install.md
- en/docs/setup/enterprise-apk-install.md
- en/mkdocs.yml
Adding enterprise version changes
> Adding enterprise version changes

- en/docs/control-plane/api-management/control-plane-api-management-overview.md
- en/docs/control-plane/apk-as-gateway-in-apim/api-management/control-plane-api-management-overview.md
Removing application level basic and api key auth from docs
> Removing application level basic and api key auth from docs

- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/get-started/quick-start-guide-with-cp.md
- en/docs/get-started/quick-start-guide.md
> Adding changes to notes

- en/docs/administration/prometheus-metric-support.md
PR to fix https://github.com/wso2/docs-apk/issues/604 in the main branch
> Update Prometheus documentation

- en/docs/setup/analytics/configure-analytics-for-choreo-insights.md
- en/docs/setup/analytics/configure-analytics-for-elk-stack.md
> Fixes a minor formatting issue in the ELK analytics documentation.
> [1.1.0] Fix ELK analytics formatting issues

- en/docs/catalogs/samples/api-cr.md
> Fixed the broken link identified.
> Ensure all links in the documentation are functioning correctly.
> - Fixed the identified broken link.
> - Re-run the script to ensure all broken links are fixed properly.
> [1.1.0] Fix Missed Broken Link

- en/docs/administration/prometheus-metric-support.md
This PR is the fix for https://github.com/wso2/docs-apk/issues/604 for 1.1.0
> [1.1.0] Update Prometheus documentation

- en/docs/assets/css/apktheme.css
- en/mkdocs.yml
- en/theme/material/partials/header.html
Changing to 1.2.0 and adding WIP banner
> Changing to 1.2.0 and adding WIP banner

- en/docs/administration/aiproviders/configure-ai-providers-customai.md
- en/docs/administration/aiproviders/configure-ai-providers-overview.md
- en/docs/create-api/create-and-deploy-apis/ai/ai-api-overview.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-crs.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-rest-api.md
- en/mkdocs.yml
Adding AI Providers and AI APIs related docs
> Adding AI Providers and AI APIs related docs

- en/docs/administration/airatelimitpolicy/configure-ai-ratelimit-policies-overview.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-crs.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-rest-api.md
- en/mkdocs.yml
> Add AI ratelimit related document

- en/docs/about-apk/FAQs.md
- en/docs/about-apk/about-this-release.md
- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/control-plane-configuration.md
- en/docs/control-plane/control-plane-deployment.md
- en/docs/control-plane/deploy-apim-apk-agent.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/customize-installation.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
- en/docs/index.md
- en/docs/setup/enterprise-apim-apk-agent-install.md
- en/docs/setup/enterprise-apk-install.md
- en/docs/setup/uninstall.md
> Change version to 1.2.0-alpha

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/start-apk-cp.md
> Change versions

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/get-started/quick-start-guide-as-gateway.md
> Fixing doc samples

- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/includes/start-apk-cp.md
> Change path

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/start-apk-cp.md
> Change apim version

- en/docs/about-apk/FAQs.md
- en/docs/control-plane/api-management/control-plane-create-and-deploy-graphql-apis.md
- en/docs/control-plane/api-management/control-plane-create-and-deploy-rest-apis.md
- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/deploy-apim-apk-agent.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/graphql/create-graphql-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-using-rest-api.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-versions.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/get-started/quick-start-guide-with-cp.md
- en/docs/get-started/quick-start-guide.md
- en/docs/includes/apk-conf-cr-deploy.md
- en/docs/includes/apk-conf-undeploy.md
- en/docs/includes/create-apk-conf-api.md
- en/docs/includes/customize-installation.md
- en/docs/includes/direct-deploy.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
- en/docs/index.md
- en/docs/setup/enterprise-apim-apk-agent-install.md
- en/docs/setup/enterprise-apk-install.md
- en/docs/setup/uninstall.md
> Changing doc to 1.2.0-beta

- en/docs/about-apk/FAQs.md
- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/deploy-apim-apk-agent.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/customize-installation.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
- en/docs/index.md
- en/docs/setup/enterprise-apim-apk-agent-install.md
- en/docs/setup/enterprise-apk-install.md
- en/docs/setup/uninstall.md
> Change the version

- en/docs/control-plane/api-management/control-plane-create-and-deploy-ai-apis.md
- en/docs/control-plane/apk-as-gateway-in-apim/api-management/control-plane-create-and-deploy-ai-apis.md
- en/mkdocs.yml
Adding AI API creation from APIM flows
> Adding AI API creation from APIM flows

- en/docs/control-plane/api-management/control-plane-api-management-overview.md
- en/docs/control-plane/apk-as-gateway-in-apim/api-management/control-plane-api-management-overview.md
Update features overview with APIM
> Update features overview with APIM

- en/docs/catalogs/crds/subscription_types.md
> Add subscription catalog changes

- en/docs/catalogs/crds/aiprovider_types.md
- en/docs/catalogs/crds/airatelimitpolicy_types.md
- en/docs/catalogs/crds/backend_types.md
- en/docs/catalogs/samples/airatelimitpolicy copy.md
- en/docs/catalogs/samples/airatelimitpolicy.md
- en/docs/catalogs/samples/backend.md
- en/docs/catalogs/samples/grpc-route.md
- en/docs/catalogs/samples/subscription.md
- en/mkdocs.yml
> Add grpc route

- en/docs/about-apk/about-this-release.md
Update about this release page
> Update about this release page

- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-rest-api.md
> Refactor AI API docs

- en/docs/about-apk/FAQs.md
- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/deploy-apim-apk-agent.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/customize-installation.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
- en/docs/index.md
- en/docs/setup/enterprise-apim-apk-agent-install.md
- en/docs/setup/enterprise-apk-install.md
- en/docs/setup/uninstall.md
> Change version

- en/docs/setup/enterprise-apk-install.md
Adding 1.2.0 arm image values yaml for enterprise
> Adding 1.2.0 arm image values yaml for enterprise

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/start-apk-cp.md
Adding APIM CP GA helm chart version
> Adding APIM CP GA helm chart version

- en/docs/assets/versions.json
> Adding 1.2.0 for doc versions

- en/mkdocs.yml
- en/theme/material/partials/header.html
> Remove WIP banner in 1.2.0

- en/mkdocs.yml
> Changing site url

- en/docs/about-apk/FAQs.md
- en/docs/administration/configurations/configure-logs-adapter.md
- en/docs/administration/configurations/configure-logs-enforcer.md
- en/docs/administration/configurations/configure-logs-overview.md
- en/docs/administration/configurations/configure-logs-router.md
- en/docs/administration/distributed-tracing.md
- en/docs/catalogs/samples/grpc-route.md
- en/docs/control-plane/deploy-apim-apk-agent.md
- en/docs/get-started/downloadFile.js
- en/docs/get-started/quick-start-guide.md
- en/docs/includes/customize-installation.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
- en/docs/index.md
- en/docs/setup/Customize-Configurations.md
- en/docs/setup/analytics/configure-analytics-for-choreo-insights.md
- en/docs/setup/analytics/configure-analytics-for-elk-stack.md
- en/docs/setup/analytics/configure-analytics-for-moesif.md
- en/docs/setup/configure-hpa.md
- en/docs/setup/enterprise-apim-apk-agent-install.md
- en/docs/setup/enterprise-apk-install.md
- en/docs/setup/identity-platform/idp/asgardeo-idp.md
- en/docs/setup/identity-platform/idp/auth0-idp.md
- en/docs/setup/identity-platform/idp/third-party-idp.md
- en/docs/setup/prerequisites.md
- en/docs/setup/production-deployment-guideline.md
- en/mkdocs.yml
Fixes the issues labelled in https://github.com/wso2/docs-apk/issues/658 for 1.2.0
> [1.2.0] Fix documentation issues 

- en/theme/material/partials/header.html
Adding cond and win contest banner
> Adding code and win contest banner

- en/theme/material/partials/header.html
> Remove apk contest banner

- en/mkdocs.yml
- en/theme/material/partials/header.html
> Changing to 1.3.0 and adding WIP banner
> Change version to 1.3.0 and add WIP banner

- en/docs/control-plane/api-management/api-policies/model-based-round-robin.md
- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/model-based-round-robin-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/model-based-round-robin-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/overview.md
- en/mkdocs.yml
Adding model based round robin documentation
> Adding model based round robin documentation

- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/model-based-round-robin-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/model-based-round-robin-via-rest-api.md
Fixing ai model based round robin docs
> Fixing ai model based round robin docs

- en/docs/control-plane/api-management/control-plane-create-and-deploy-ai-apis.md
- en/docs/control-plane/api-management/control-plane-create-and-deploy-graphql-apis.md
- en/docs/control-plane/api-management/control-plane-create-and-deploy-rest-apis.md
- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/graphql/create-graphql-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-with-multiple-proto-files.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-version.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/get-started/quick-start-guide-with-cp.md
- en/docs/get-started/quick-start-guide.md
- en/docs/includes/apk-conf-cr-deploy.md
- en/docs/includes/apk-conf-undeploy.md
- en/docs/includes/create-apk-conf-api.md
- en/docs/includes/direct-deploy.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
- en/docs/setup/cicd/building-a-pipeline.md
> Update version in docs

- en/docs/create-api/weighted-routing/weighted-routing-via-crs.md
- en/mkdocs.yml
> Adding Weighted Routing Documentation to 1.3.0
> Adding weighted routing documentation

- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/model-based-round-robin-via-crs.md
- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/model-based-round-robin-via-rest-api.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-crs.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/graphql/create-graphql-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-with-multiple-proto-files.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-version.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/api-versions/semver-based-intelligent-routing.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/mtls.md
- en/docs/get-started/quick-start-guide.md
> Update Bearer keyword

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/start-apk-cp.md
> Update doc links

- en/docs/create-api/weighted-routing/weighted-routing-via-crs.md
> Modification in weighted routing documentation to add a test to quickly verify weights of responses received.
> Modifying weighted routing documentation

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/customize-installation.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
> Update docs for beta

- en/docs/control-plane/control-plane-configuration.md
- en/docs/control-plane/control-plane-deployment.md
- en/docs/control-plane/deploy-apim-apk-agent.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/get-started/quick-start-guide-with-cp.md
- en/docs/get-started/quick-start-guide.md
- en/docs/includes/create-apk-conf-api.md
- en/docs/includes/customize-installation.md
- en/docs/includes/direct-deploy.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
> Revamp docs to 1.3.0 rc

- en/docs/about-apk/FAQs.md
- en/docs/about-apk/about-this-release.md
- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-using-crs.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-using-rest-api.md
- en/docs/index.md
- en/docs/setup/Customize-Configurations.md
- en/docs/setup/enterprise-apim-apk-agent-install.md
- en/docs/setup/enterprise-apk-install.md
- en/docs/setup/uninstall.md
> Revamping docs to 1.3.0 rc

- en/docs/create-api/create-and-attach-api-policies/backend-jwt-token-manipulation/backend-jwt-token-manipulation-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/header-modifier-filters/header-modifier-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/interceptors/interceptors-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/mirror-request-filters/mirror-request-via-rest-api.md
- en/docs/create-api/create-and-attach-api-policies/redirect-request-filters/redirect-request-via-rest-api.md
- en/docs/create-api/create-and-deploy-apis/ai/create-ai-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/graphql/create-graphql-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-using-rest-api.md
- en/docs/create-api/create-and-deploy-apis/grpc/create-grpc-api-with-multiple-proto-files.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-circuit-breaker.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-timeout.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-rest-api.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/docs/develop-and-deploy-api/api-properties/api-properties.md
- en/docs/develop-and-deploy-api/api-scopes/api-scopes.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-version.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/mtls.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/oauth2.md
Changing sample apk confs endpoint to new version
> Changing sample apk confs endpoint to new version

- en/docs/create-api/create-and-attach-api-policies/model-based-round-robin/overview.md
- en/docs/create-api/weighted-routing/overview.md
- en/docs/create-api/weighted-routing/weighted-routing-via-crs.md
- en/docs/create-api/weighted-routing/weighted-routing-via-rest-api.md
- en/mkdocs.yml
> Fixes #707 
> Added documentation on weighted routing via REST API (using the APK-Conf file) as well as updated the documentation on weighted routing via CRs.
> Updating weighted routing documentation

- en/docs/includes/start-apk-cp.md
> Fixing dp to cp apim command

- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
> Fixing issues with VM pattern

- en/docs/get-started/quick-start-guide.md
- en/docs/includes/start-apk.md
> Fixing QSG issues

- en/docs/setup/cicd/building-a-pipeline.md
> 1.2.0 redirection fix

- en/theme/material/partials/header.html
> Update doc header

- en/docs/assets/files/configure-permissions/apk-specific-permission.yaml
- en/docs/setup/cert-manager.md
- en/docs/setup/configuring-permissions/configuring-roles-and-rolebindings.md
- en/mkdocs.yml
This PR adds documentation about Roles, RoleBindings, ClusterRoles and ClusterRoleBindings included in the APK installation.
> [1.2.0] Add documentation on Roles and RoleBindings

- en/docs/api-management-overview/tools-for-api-development.md
- en/docs/control-plane/api-management/control-plane-add-apk-gateway.md
- en/docs/control-plane/apk-as-gateway-in-apim/api-management/control-plane-add-apk-gateway.md
- en/docs/control-plane/apk-as-gateway-in-apim/api-management/control-plane-create-and-deploy-rest-apis.md
- en/docs/create-api/create-and-attach-api-policies/cors/enable-cors-via-rest-api.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-circuit-breaker.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-retry-policy.md
- en/docs/create-api/manage-service-endpoint/manage-resiliency-timeout.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-crs.md
- en/docs/create-api/manage-service-endpoint/manage-security-via-rest-api.md
- en/docs/create-api/rate-limiting/add-new-rate-limiting-policies-via-rest-api.md
- en/docs/develop-and-deploy-api/api-definition-endpoint/api-definition-endpoint.md
- en/docs/develop-and-deploy-api/api-scopes/api-scopes.md
- en/docs/develop-and-deploy-api/api-versions/create-an-api-version.md
- en/docs/develop-and-deploy-api/api-versions/default-version.md
- en/docs/develop-and-deploy-api/endpoints/prod-sand-endpoints.md
- en/docs/develop-and-deploy-api/security/authentication/enable-api-security/oauth2.md
- en/docs/get-started/quick-start-guide.md
- en/docs/includes/create-apk-conf-api.md
- en/docs/includes/post-create-apk-conf-api.md
> Definition file links, grammar, and yaml configurations view code updates

- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/setup/apim-deploy-with-db.md
- en/mkdocs.yml
Adding apim cp with mysql db docs
> Adding apim cp with mysql db docs

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/start-apk-cp.md
- en/docs/setup/apim-deploy-with-db.md
Adding changes related APIM helm chart 4.5.0-1
Fixes https://github.com/wso2/apk/issues/2986
> Adding changes related APIM helm chart 4.5.0-1

- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
Fixing issues in cp to dp vm docs
> Fixing issues in cp to dp vm docs

- en/mkdocs.yml
> Change version to 2.0.0

- en/docs/get-started/quick-start-guide.md
- en/docs/includes/start-apk.md
> Fix image path

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-k8s.md
- en/docs/control-plane/apk-as-gateway-in-apim/start-apk-cp-to-dp-vms.md
- en/docs/control-plane/start-apk-dp-to-cp-k8s.md
- en/docs/control-plane/start-apk-dp-to-cp-vms.md
- en/docs/get-started/quick-start-guide-as-gateway.md
- en/docs/includes/customize-installation.md
- en/docs/includes/start-apk-cp.md
- en/docs/includes/start-apk.md
- en/docs/setup/cicd/building-a-pipeline.md
- en/docs/setup/deployment/apk-dataplane-per-cluster.md
- en/docs/setup/webhook-customization.md
> Improve doc for 1.3.0-1

- en/docs/control-plane/apk-as-gateway-in-apim/apk-as-gateway-in-apim-qsg.md
- en/docs/get-started/quick-start-guide-as-gateway.md
> Fixing issues in CP QSG
